version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm ci

      - run:
          name: Build
          command: npm run build

  misc:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm ci

      - run:
          name: Javascript linter
          command: npm run lint

      - run:
          name: Vulnerability audit
          command: npm audit

workflows:
  version: 2
  build_and_misc:
    jobs:
      - build
      - misc
